[[themes]]
name = "Tokyo Night Day"
[themes.palette]
background = "#d0d5e3"
foreground = "#6172b0"
black = "#a1a6c5"
red = "#f52a65"
green = "#587539"
yellow = "#8c6c3e"
blue = "#2e7de9"
magenta = "#9854f1"
cyan = "#007197"
white = "${white}"
bright_black = "#e1e2e7"
bright_red = "#c64343"
bright_green = "#387068"
bright_yellow = "#b15c00"
bright_blue = "#188092"
bright_magenta = "#d20065"
bright_cyan = "#006a83"
bright_white = "#3760bf"
