[[themes]]
name = "Tokyo Night Moon"
[themes.palette]
background = "#1e2030"
foreground = "#828bb8"
black = "#444a73"
red = "#ff757f"
green = "#c3e88d"
yellow = "#ffc777"
blue = "#82aaff"
magenta = "#c099ff"
cyan = "#86e1fc"
white = "${white}"
bright_black = "#222436"
bright_red = "#c53b53"
bright_green = "#4fd6be"
bright_yellow = "#ff966c"
bright_blue = "#65bcff"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#c8d3f5"
