[[themes]]
name = "Tokyo Night Storm"
[themes.palette]
background = "#1f2335"
foreground = "#a9b1d6"
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "${white}"
bright_black = "#24283b"
bright_red = "#db4b4b"
bright_green = "#73daca"
bright_yellow = "#ff9e64"
bright_blue = "#2ac3de"
bright_magenta = "#ff007c"
bright_cyan = "#89ddff"
bright_white = "#c0caf5"
